---
development:
  DB_FILENAME: db/local/dev.db
  Google_Translation_Token: your_google_translation_token
  GOOGLE_MAPS_KEY: your_google_maps_key
  OPENAI_TOKEN: your_open_ai_token
  SESSION_SECRET: your_session_secret_key

test:
  DB_FILENAME: db/local/test.db
  Google_Translation_Token: your_google_translation_token
  GOOGLE_MAPS_KEY: your_google_maps_key
  OPENAI_TOKEN: your_open_ai_token
  SESSION_SECRET: your_session_secret_key

production:
  Google_Translation_Token: your_google_translation_token
  GOOGLE_MAPS_KEY: your_google_maps_key
  OPENAI_TOKEN: your_open_ai_token
  SESSION_SECRET: your_session_secret_key
