---
# Name your file secrets.yml

development:
  # Infrastructure
  DB_FILENAME: db/local/dev.db
  GOOGLE_MAPS_KEY: your_google_maps_key
  OPENAI_TOKEN: your_open_ai_token
  # Application
  SESSION_SECRET: your_session_secret_key

test:
  # Infrastructure
  DB_FILENAME: db/local/test.db
  GOOGLE_MAPS_KEY: your_google_maps_key
  OPENAI_TOKEN: your_open_ai_token
  # Application
  SESSION_SECRET: your_session_secret_key

production:
  # Infrastructure
  GOOGLE_MAPS_KEY: your_google_maps_key
  OPENAI_TOKEN: your_open_ai_token
  # Application
  SESSION_SECRET: your_session_secret_key
